const STATUS_LOADED = 1;
const STATUS_PROCESSED = 2
const STATUS_EDITING = 3;
const STATUS_DELETE = 4;
const STATUS_SAVED = 5;

const STATUS_NOT_EXIST = 6;
const STATUS_NOT_ANSWER = 7;
const STATUS_REPEATED = 8;
module.exports = {
  STATUS_LOADED,
  STATUS_PROCESSED,
  STATUS_EDITING,
  STATUS_DELETE,
  STATUS_SAVED,
  STATUS_NOT_EXIST,
  STATUS_NOT_ANSWER,
  STATUS_REPEATED
};